FROM python:3.5

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -qqy apt-utils && apt-get install -qqy libxml2-utils

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt \
    && groupadd -r django \
    && useradd -r -g django django

RUN mkdir -p /etc/xml \
    && bash -c "$(curl -fsSL https://raw.githubusercontent.com/scieloorg/packtools/master/scripts/install_xml_catalog.sh)"


COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN mkdir -p /app/media
RUN chown -R django /app

COPY ./compose/django/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh

VOLUME /app/media
WORKDIR /app

USER django

ENTRYPOINT ["/entrypoint.sh"]
