# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0002_deposit_depositor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='frontdesk.Package')),
            ],
        ),
    ]
