# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0003_packagemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='virus_scan_details',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='package',
            name='virus_scan_status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='queued', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='package',
            name='virus_scan_status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='virus_scan_status', when=set(['uninfected', 'undetermined', 'infected'])),
        ),
    ]
