# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 19:45
from __future__ import unicode_literals

import db.fields
from django.db import migrations, models
import django.db.models.deletion
import frontdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0005_xmlmembercontrolattrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMemberVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', db.fields.ChecksummedFileField(max_length=1024, upload_to=frontdesk.models._make_file_path)),
                ('package_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='frontdesk.PackageMember')),
            ],
        ),
    ]
